name: AnvilRenameCancel
version: '1.0-SNAPSHOT'
main: com.anvilrenamecancel.AnvilRenameCancel
api-version: 1.16
author: MyTruth
website: minetruth.com
description: This plugin blocks the anvil rename event
